config/routes.rb
Rails.application.routes.draw do
  get "/en/*path", to: redirect('/%{path}', status: 301)

  scope "(:locale)", locale: LocalesScope.scoped_locales_regex do
    scope 'pages' do
      get 'one', to: 'pages#one', as: 'one'
      get 'two', to: 'pages#two', as: 'two'
      get 'three', to: 'pages#three', as: 'three'
    end
    
    root to: 'pages#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/locales_scope.rb
module LocalesScope
  SUPPORTED_LOCALES = I18n.available_locales
  SCOPED_LOCALES = SUPPORTED_LOCALES - [I18n.default_locale]
  
  def self.supported_locales_regex
    /#{supported_locales_regex_map}/.freeze
  end

  def self.scoped_locales_regex
    /#{scoped_locales_regex_map}/.freeze
  end

  private

  def self.reordered_supported_locales
    # yuck
    SUPPORTED_LOCALES.select {|l| l.to_s.include?('-')} + SUPPORTED_LOCALES.reject {|l| l.to_s.include?('-')} 
  end

  def self.supported_locales_regex_map
    reordered_supported_locales.join("|")
  end
  
  def self.scoped_locales_regex_map
    (reordered_supported_locales  - [I18n.default_locale]).join("|")
  end
end

app/models/routes.rb
module Routes
  SUPPORTED_LOCALES = I18n.available_locales
  SCOPED_LOCALES = SUPPORTED_LOCALES - [I18n.default_locale]
  
  def self.supported_locales_regex
    /#{supported_locales_regex_map}/.freeze
  end

  def self.scoped_locales_regex
    /#{scoped_locales_regex_map}/.freeze
  end

  private

  def self.reordered_supported_locales
    # yuck
    SUPPORTED_LOCALES.select {|l| l.to_s.include?('-')} + SUPPORTED_LOCALES.reject {|l| l.to_s.include?('-')} 
  end

  def self.supported_locales_regex_map
    reordered_supported_locales.join("|")
  end
  
  def self.scoped_locales_regex_map
    (reordered_supported_locales  - [I18n.default_locale]).join("|")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include LocalizationHandling
end

app/controllers/concerns/localization_handling.rb
module LocalizationHandling
  extend ActiveSupport::Concern

  included do
    around_action :switch_locale
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/localization_helper.rb
module LocalizationHelper
  def current_path_in_locale(locale, options={})
    locale = nil if locale == I18n.default_locale

    url_for(request.query_parameters.merge(locale: locale, **options))
  end

  def hreflang_tags
    links = LocalesScope::SCOPED_LOCALES.map do |locale|
      tag.link(rel: "alternate", hreflang: locale.to_s.downcase, href: current_path_in_locale(locale, only_path: false))
    end

    links.prepend(tag.link(rel: "alternate", hreflang: "x-default", href: current_path_in_locale(I18n.default_locale, only_path: false)))

    links.join.html_safe
  end

  def canonical_url_tag
    tag.link(rel: "canonical", href: current_path_in_locale(I18n.locale, only_path: false))
  end
end

app/views/layouts/_language_picker.html.erb
<div style="display: flex; align-items: baseline; margin: 12px 0; ">
  <p>Switch Locale: </p>

  <select id="locale-picker" style="margin-left: 6px;">
    <% I18n.available_locales.each do |locale| %>
      <option value="<%= current_path_in_locale(locale) %>" <%= "selected" if I18n.locale == locale %>>
        <%= I18n.t("locales.#{locale}") %>
      </option>
    <% end %>
  </select>

  <script>
    document.getElementById("locale-picker").addEventListener("change", (e) => {
      document.location = e.target.value;
    })
  </script>
</div>

app/views/layouts/_meta.html.erb
<strong>Meta Information</strong><br>
<code>
  <% snippet = capture do %>
    <%= canonical_url_tag %>
  <% end %>
  <%= escape_once snippet %>
  <br>

  <% hreflang_tags.split(">").each do |tag| %>
    <% snippet = capture do %>
      <%= tag %>>
    <% end %>
    <%= escape_once snippet %>
    <br>
  <% end %>
</code>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>LocalizedRoutesExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= canonical_url_tag %>
    <%= hreflang_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

    <style>
      body {
        font-family: sans-serif;
      }
    </style>
  </head>

  <body>
    <header style="margin-bottom: 32px; padding: 16px 0 16px;">
      <div class="container">
        <nav>
          <ul style="display: flex; list-style: none; margin: 0; padding: 0;">
            <li style="margin: 0 6px;"><%= link_to root_path, root_path %></li>
            <li style="margin: 0 6px;"><%= link_to one_path, one_path %></li>
            <li style="margin: 0 6px;"><%= link_to two_path, two_path %></li>
            <li style="margin: 0 6px;"><%= link_to three_path, three_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    
    <main style="min-height: calc(100vh - 172px);">
      <div class="container">
        <%= render partial: "layouts/meta" %>
        
        <%= yield %>
      </div>
    </main>

    <footer>
      <div class="container" style="display: flex; justify-content: flex-end;">
        <%= render partial: "layouts/language_picker" %>
      </div>
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
<h1><%= I18n.t("pages.root.title") %></h1>
<p><%= I18n.t("pages.root.body") %></p>

app/views/pages/one.html.erb
<h1><%= I18n.t("pages.one.title") %></h1>
<p><%= I18n.t("pages.one.body") %></p>

app/views/pages/three.html.erb
<h1><%= I18n.t("pages.three.title") %></h1>
<p><%= I18n.t("pages.three.body") %></p>

app/views/pages/two.html.erb
<h1><%= I18n.t("pages.two.title") %></h1>
<p><%= I18n.t("pages.two.body") %></p>